### ISSUE TITLE
% CPU and GPU usage

### ISSUE THREAD

**Issue by FredrikNoren** [robotty/simple-process-stats#18]
Hi, this crate looks amazing! Any chance it could also output % CPU and GPU usage?

**Comment by RAnders00** [comment]
% CPU is already easy: Add `cpu_time_user` and `cpu_time_kernel` and divide by time since process start.

I don‘t have any plans on adding GPU support to this crate, since I made it for monitoring a service on a server, and I plan on keeping it simple and only for that.
