### ISSUE TITLE
please get rid of `async`

### ISSUE THREAD

**Issue by zseri** [robotty/simple-process-stats#19]
As this crate only uses async features on linux to read the proc filesystem, and these are basically instant and pretty small, using async features and potentially offloading the stat file read to a separate thread isn't really worth it. It pulls in tokio, which is a pretty big dependency, and I think it might be a good idea to just get rid of `async` usage in this crate, especially, because nothing async at all is used on windows or macos inside of this crate.

**Comment by RAnders00** [comment]
Fixed via 8dd5fb03edb666bacd194e051098c9b4d59e0ebc
