### ISSUE TITLE
Unit mismatch for CPU time on M1 macs

### ISSUE THREAD

**Issue by kathoum** [robotty/simple-process-stats#21]
I think that this library is affected by the same bug as [htop issue 368](https://github.com/htop-dev/htop/issues/368) and [firefox bug 1753310](https://bugzilla.mozilla.org/show_bug.cgi?id=1753310).

I don't have access to a M1 mac so I can't confirm.

As reported in the above bugs, the correct way to convert from "absolute mach time" to (nano-)seconds is documented in "Apply Timebase Information to Mach Absolute Time Values" in https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code

**Comment by RAnders00** [comment]
I would most certainly appreciate a PR!

**Comment by RAnders00** [comment]
Fixed via 7dfa6c0221a7c8c551f2720488e8d72d82a2b849 (#25)
